spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gp?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456

# mybatis配置，扫描所有*.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 通用mapper配置
mapper:
  # 设定主键自增回写SQL
  identity: MYSQL

# pagehelper分页插件配置
pagehelper:
  # 指定分页方言，否则分页插件会自动检测当前的数据库链接，自动选择合适的分页方式
  # 配置时，可以使用下面的缩写值：
  # oracle,mysql,mariadb,sqlite,hsqldb,postgresql,db2,sqlserver,informix,h2,sqlserver2012,derby
  # 特别注意：使用 SqlServer2012 数据库时，需要手动指定为 sqlserver2012，否则会使用 SqlServer2005 的方式进行分页。
  helperDialect: mysql
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），
  # 会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数
  supportMethodsArguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值，
  # 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable
  # 当supportMethodsArguments=true时，分页插件会从查询方法的参数值中，自动根据params配置的字段中取值，查找到合适的值时就会自动分页
  params: pageNum=pageNum;pageSize=pageSize;
  # 当该参数设置为true时，如果pageSize=0，就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是Page类型）
  pageSizeZero: false