spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gp?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456

# mybatis配置，扫描所有*.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 通用mapper配置
mapper:
  # 设定主键自增回写SQL
  identity: MYSQL
